// <auto-generated />
using System;
using Calorie_Tracker.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Calorie_Tracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250604213129_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Calorie_Tracker.data.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Caffeine")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Calorie")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Fats")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GramsInPortion")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Protein")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Salts")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calorie = 1400m,
                            Fats = 13.4m,
                            GramsInPortion = 160m,
                            Name = "Pizza",
                            Protein = 10m,
                            Salts = 14m
                        },
                        new
                        {
                            Id = 2,
                            Calorie = 900m,
                            Fats = 16.4m,
                            GramsInPortion = 30m,
                            Name = "Spaghetti",
                            Protein = 20m,
                            Salts = 18m
                        },
                        new
                        {
                            Id = 3,
                            Calorie = 165m,
                            Fats = 3.6m,
                            GramsInPortion = 100m,
                            Name = "Chicken Breast",
                            Protein = 31m,
                            Salts = 0.7m
                        },
                        new
                        {
                            Id = 4,
                            Calorie = 52m,
                            Fats = 0.2m,
                            GramsInPortion = 150m,
                            Name = "Apple",
                            Protein = 0.3m,
                            Salts = 0m
                        },
                        new
                        {
                            Id = 5,
                            Calorie = 89m,
                            Fats = 0.3m,
                            GramsInPortion = 120m,
                            Name = "Banana",
                            Protein = 1.1m,
                            Salts = 0m
                        },
                        new
                        {
                            Id = 6,
                            Calorie = 55m,
                            Fats = 0.6m,
                            GramsInPortion = 100m,
                            Name = "Broccoli",
                            Protein = 3.7m,
                            Salts = 0.05m
                        },
                        new
                        {
                            Id = 7,
                            Calorie = 208m,
                            Fats = 13m,
                            GramsInPortion = 100m,
                            Name = "Salmon",
                            Protein = 20m,
                            Salts = 0.1m
                        },
                        new
                        {
                            Id = 8,
                            Calorie = 160m,
                            Fats = 15m,
                            GramsInPortion = 100m,
                            Name = "Avocado",
                            Protein = 2m,
                            Salts = 0.01m
                        },
                        new
                        {
                            Id = 9,
                            Calorie = 130m,
                            Fats = 0.3m,
                            GramsInPortion = 100m,
                            Name = "Rice",
                            Protein = 2.7m,
                            Salts = 0m
                        },
                        new
                        {
                            Id = 10,
                            Calorie = 303m,
                            Fats = 14m,
                            GramsInPortion = 120m,
                            Name = "Cheeseburger",
                            Protein = 17m,
                            Salts = 1.2m
                        },
                        new
                        {
                            Id = 11,
                            Calorie = 312m,
                            Fats = 15m,
                            GramsInPortion = 100m,
                            Name = "French Fries",
                            Protein = 3.4m,
                            Salts = 0.6m
                        },
                        new
                        {
                            Id = 12,
                            Calorie = 47m,
                            Fats = 0.1m,
                            GramsInPortion = 130m,
                            Name = "Orange",
                            Protein = 0.9m,
                            Salts = 0m
                        },
                        new
                        {
                            Id = 13,
                            Calorie = 155m,
                            Fats = 11m,
                            GramsInPortion = 60m,
                            Name = "Egg",
                            Protein = 13m,
                            Salts = 0.1m
                        },
                        new
                        {
                            Id = 14,
                            Calorie = 42m,
                            Fats = 1m,
                            GramsInPortion = 100m,
                            Name = "Milk",
                            Protein = 3.4m,
                            Salts = 0.05m
                        },
                        new
                        {
                            Id = 15,
                            Calorie = 59m,
                            Fats = 0.4m,
                            GramsInPortion = 150m,
                            Name = "Yogurt",
                            Protein = 10m,
                            Salts = 0.1m
                        },
                        new
                        {
                            Id = 16,
                            Calorie = 588m,
                            Fats = 50m,
                            GramsInPortion = 100m,
                            Name = "Peanut Butter",
                            Protein = 25m,
                            Salts = 1.2m
                        },
                        new
                        {
                            Id = 17,
                            Calorie = 579m,
                            Fats = 49m,
                            GramsInPortion = 100m,
                            Name = "Almonds",
                            Protein = 21m,
                            Salts = 0m
                        },
                        new
                        {
                            Id = 18,
                            Calorie = 68m,
                            Fats = 1.4m,
                            GramsInPortion = 40m,
                            Name = "Oatmeal",
                            Protein = 2.4m,
                            Salts = 0m
                        },
                        new
                        {
                            Id = 19,
                            Caffeine = 47m,
                            Calorie = 1m,
                            Fats = 0m,
                            GramsInPortion = 250m,
                            Name = "Tea",
                            Protein = 0m,
                            Salts = 0m
                        },
                        new
                        {
                            Id = 20,
                            Caffeine = 95m,
                            Calorie = 2m,
                            Fats = 0m,
                            GramsInPortion = 250m,
                            Name = "Coffee",
                            Protein = 0.3m,
                            Salts = 0m
                        });
                });

            modelBuilder.Entity("Calorie_Tracker.data.HistoryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("date");

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Grams")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Portions")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("History");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 20,
                            Grams = 181.6m,
                            Portions = 3.1m
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2025, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 18,
                            Grams = 289.6m,
                            Portions = 2.1m
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2025, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 11,
                            Grams = 391.6m,
                            Portions = 3.1m
                        },
                        new
                        {
                            Id = 4,
                            DateTime = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 6,
                            Grams = 277.2m,
                            Portions = 1.1m
                        },
                        new
                        {
                            Id = 5,
                            DateTime = new DateTime(2025, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 14,
                            Grams = 163.3m,
                            Portions = 2.8m
                        },
                        new
                        {
                            Id = 6,
                            DateTime = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 11,
                            Grams = 242.7m,
                            Portions = 2.1m
                        },
                        new
                        {
                            Id = 7,
                            DateTime = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 3,
                            Grams = 366.1m,
                            Portions = 0.6m
                        },
                        new
                        {
                            Id = 8,
                            DateTime = new DateTime(2025, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 11,
                            Grams = 121.1m,
                            Portions = 3.2m
                        },
                        new
                        {
                            Id = 9,
                            DateTime = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 18,
                            Grams = 260.1m,
                            Portions = 1.5m
                        },
                        new
                        {
                            Id = 10,
                            DateTime = new DateTime(2025, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 14,
                            Grams = 196.3m,
                            Portions = 3.2m
                        },
                        new
                        {
                            Id = 11,
                            DateTime = new DateTime(2025, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 13,
                            Grams = 117.9m,
                            Portions = 1.1m
                        },
                        new
                        {
                            Id = 12,
                            DateTime = new DateTime(2025, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 10,
                            Grams = 303.0m,
                            Portions = 3.0m
                        },
                        new
                        {
                            Id = 13,
                            DateTime = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 9,
                            Grams = 329.5m,
                            Portions = 2.7m
                        },
                        new
                        {
                            Id = 14,
                            DateTime = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 9,
                            Grams = 299.3m,
                            Portions = 2.0m
                        },
                        new
                        {
                            Id = 15,
                            DateTime = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 19,
                            Grams = 262.1m,
                            Portions = 1.2m
                        },
                        new
                        {
                            Id = 16,
                            DateTime = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 9,
                            Grams = 343.3m,
                            Portions = 0.5m
                        },
                        new
                        {
                            Id = 17,
                            DateTime = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 6,
                            Grams = 299.7m,
                            Portions = 1.2m
                        },
                        new
                        {
                            Id = 18,
                            DateTime = new DateTime(2025, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 17,
                            Grams = 127.9m,
                            Portions = 1.8m
                        },
                        new
                        {
                            Id = 19,
                            DateTime = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 14,
                            Grams = 168.3m,
                            Portions = 2.2m
                        },
                        new
                        {
                            Id = 20,
                            DateTime = new DateTime(2025, 6, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 8,
                            Grams = 326.9m,
                            Portions = 2.7m
                        },
                        new
                        {
                            Id = 21,
                            DateTime = new DateTime(2025, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 14,
                            Grams = 77.4m,
                            Portions = 2.8m
                        },
                        new
                        {
                            Id = 22,
                            DateTime = new DateTime(2025, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 18,
                            Grams = 378.5m,
                            Portions = 2.2m
                        },
                        new
                        {
                            Id = 23,
                            DateTime = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 2,
                            Grams = 236.6m,
                            Portions = 0.7m
                        },
                        new
                        {
                            Id = 24,
                            DateTime = new DateTime(2025, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 19,
                            Grams = 205.0m,
                            Portions = 1.3m
                        },
                        new
                        {
                            Id = 25,
                            DateTime = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 3,
                            Grams = 178.2m,
                            Portions = 1.9m
                        },
                        new
                        {
                            Id = 26,
                            DateTime = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 15,
                            Grams = 185.4m,
                            Portions = 2.0m
                        },
                        new
                        {
                            Id = 27,
                            DateTime = new DateTime(2025, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 12,
                            Grams = 196.3m,
                            Portions = 1.9m
                        },
                        new
                        {
                            Id = 28,
                            DateTime = new DateTime(2025, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 18,
                            Grams = 372.0m,
                            Portions = 1.2m
                        },
                        new
                        {
                            Id = 29,
                            DateTime = new DateTime(2025, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 6,
                            Grams = 319.7m,
                            Portions = 1.7m
                        },
                        new
                        {
                            Id = 30,
                            DateTime = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 3,
                            Grams = 51.0m,
                            Portions = 1.8m
                        },
                        new
                        {
                            Id = 31,
                            DateTime = new DateTime(2025, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 20,
                            Grams = 324.6m,
                            Portions = 2.8m
                        },
                        new
                        {
                            Id = 32,
                            DateTime = new DateTime(2025, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 9,
                            Grams = 398.8m,
                            Portions = 2.6m
                        },
                        new
                        {
                            Id = 33,
                            DateTime = new DateTime(2025, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 5,
                            Grams = 336.8m,
                            Portions = 1.8m
                        },
                        new
                        {
                            Id = 34,
                            DateTime = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 2,
                            Grams = 397.5m,
                            Portions = 1.2m
                        },
                        new
                        {
                            Id = 35,
                            DateTime = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 5,
                            Grams = 342.9m,
                            Portions = 0.9m
                        },
                        new
                        {
                            Id = 36,
                            DateTime = new DateTime(2025, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 1,
                            Grams = 370.7m,
                            Portions = 2.0m
                        },
                        new
                        {
                            Id = 37,
                            DateTime = new DateTime(2025, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 6,
                            Grams = 121.8m,
                            Portions = 3.1m
                        },
                        new
                        {
                            Id = 38,
                            DateTime = new DateTime(2025, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 3,
                            Grams = 219.5m,
                            Portions = 1.9m
                        },
                        new
                        {
                            Id = 39,
                            DateTime = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 5,
                            Grams = 98.6m,
                            Portions = 2.0m
                        },
                        new
                        {
                            Id = 40,
                            DateTime = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 5,
                            Grams = 275.0m,
                            Portions = 2.5m
                        },
                        new
                        {
                            Id = 41,
                            DateTime = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 8,
                            Grams = 384.1m,
                            Portions = 0.5m
                        },
                        new
                        {
                            Id = 42,
                            DateTime = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 4,
                            Grams = 301.1m,
                            Portions = 3.3m
                        },
                        new
                        {
                            Id = 43,
                            DateTime = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 12,
                            Grams = 135.6m,
                            Portions = 3.1m
                        },
                        new
                        {
                            Id = 44,
                            DateTime = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 10,
                            Grams = 102.7m,
                            Portions = 1.2m
                        },
                        new
                        {
                            Id = 45,
                            DateTime = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 17,
                            Grams = 138.2m,
                            Portions = 1.7m
                        },
                        new
                        {
                            Id = 46,
                            DateTime = new DateTime(2025, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 9,
                            Grams = 386.8m,
                            Portions = 2.3m
                        },
                        new
                        {
                            Id = 47,
                            DateTime = new DateTime(2025, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 11,
                            Grams = 297.0m,
                            Portions = 1.2m
                        },
                        new
                        {
                            Id = 48,
                            DateTime = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 15,
                            Grams = 177.7m,
                            Portions = 2.7m
                        },
                        new
                        {
                            Id = 49,
                            DateTime = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 15,
                            Grams = 371.6m,
                            Portions = 2.7m
                        },
                        new
                        {
                            Id = 50,
                            DateTime = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoodId = 17,
                            Grams = 384.2m,
                            Portions = 2.1m
                        });
                });

            modelBuilder.Entity("Calorie_Tracker.data.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("date");

                    b.Property<int?>("FoodId")
                        .HasColumnType("integer");

                    b.Property<string>("Noted")
                        .IsRequired()
                        .HasMaxLength(514)
                        .HasColumnType("character varying(514)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 1,
                            Noted = "Leftover pizza"
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 4,
                            Noted = "Too salty, reduce portion next time"
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 7,
                            Noted = "Tried grilled tofu, decent protein source"
                        },
                        new
                        {
                            Id = 4,
                            DateTime = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 13,
                            Noted = "Had too much chocolate"
                        },
                        new
                        {
                            Id = 5,
                            DateTime = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 19,
                            Noted = "Coffee gave slight jitters, reduce caffeine?"
                        },
                        new
                        {
                            Id = 6,
                            DateTime = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Noted = "Skipped breakfast"
                        },
                        new
                        {
                            Id = 7,
                            DateTime = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Noted = "Felt energetic after lunch"
                        },
                        new
                        {
                            Id = 8,
                            DateTime = new DateTime(2025, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Noted = "Meal timing was off"
                        },
                        new
                        {
                            Id = 9,
                            DateTime = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Noted = "Try more vegetarian meals next week"
                        },
                        new
                        {
                            Id = 10,
                            DateTime = new DateTime(2025, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Noted = "Late dinner caused bloating"
                        });
                });

            modelBuilder.Entity("Calorie_Tracker.data.HistoryRecord", b =>
                {
                    b.HasOne("Calorie_Tracker.data.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("Calorie_Tracker.data.Note", b =>
                {
                    b.HasOne("Calorie_Tracker.data.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId");

                    b.Navigation("Food");
                });
#pragma warning restore 612, 618
        }
    }
}
